### ISSUE TITLE
getting things going

### ISSUE THREAD

**Issue by ghost** [albrow/temple-example#2]
I a giving this a try to see how humble feels.

i have installed it all, but cant get People or TODO to run.
People looks a bit easier.

i did a go get ./... and it pulls all dependencies. all good.
gopherjs is installed

So for people:
1. are client and server separate processes to be run ?
when i try to run the server it dies....
go run server.go
# github.com/go-humble/examples/people/shared/models

../shared/models/person.go:11: undefined: zoom.ModelType
../shared/models/person.go:19: pool.Register undefined (type *zoom.Pool has no field or method Register)

**Comment by ghost** [comment]
btw the generator in server.go looks like a pretty smart pattern.

//go:generate temple build ../shared/templates/templates ../shared/templates/templates.go --partials=../shared/templates/partials --layouts=../shared/templates/layouts
//go:generate gopherjs build ../client/main.go -o public/js/app.js

But for deployment, you dont want to generate of course, so i guess it might be good to distinugish between DEV and PROUCTION

**Comment by ghost** [comment]
OK, i see zoom is a redis client i guess ??  i will install it and see if it helps

**Comment by ghost** [comment]
i got redis installed and in the zoom repo, all tests pass.
I have never used redis before, but it seems to be alive and working.

**Comment by albrow** [comment]
@gedw99 I'm sorry for the lack of documentation in the examples repo. The two examples are simply not finished, which is why I haven't gotten around to documenting them yet. I hopefully will be able to work on them this weekend. If it's okay with you, I'll leave this issue open so that I can use it to keep you updated.

**Comment by ghost** [comment]
Ah that explains it. Will try when finished. It looks pretty nice so far

**Comment by albrow** [comment]
TodoMVC is now functionally complete and documented: https://github.com/go-humble/examples/tree/master/todomvc.

**Comment by ghost** [comment]
great. will give it a shot
