### ISSUE TITLE
albrow/zoom: ModelType renamed to Collection

### ISSUE THREAD

**Issue by pwaller** [albrow/temple-example#3]
https://github.com/albrow/zoom/commit/f4befd6 renames ModelType to Collection, which is used by [Person](https://github.com/go-humble/examples/blob/031d0d83d6f3d796b27c8005691053dfa1c8a38c/people/shared/models/person.go#L11).

**Comment by albrow** [comment]
Fixed in 4fccd5189f5e808508d45d86755372cf44ec0630
